services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 10

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - api
    ports:
      - "5173:80"
