spring:
  datasource:
    url: jdbc:h2:mem:transfersdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
  h2:
    console:
      enabled: false
  main:
    banner-mode: off

logging:
  level:
    org.springframework: warn
    org.hibernate.SQL: off
